import crypto from 'crypto';

export interface CapturedPlan {
  planHash: string;
  merkleRoot: string;
  stepProof: string;
  goal: string;
  timestamp: string;
}

export class ArmorIQUserScope {
  constructor(public userEmail: string, private apiKey: string) {}

  /**
   * Captures the plan generated by the AI agent and seals it with a cryptographic hash.
   */
  async capturePlan(llmName: string, prompt: string, plan: { goal: string; steps: any[] }): Promise<CapturedPlan> {
    const timestamp = new Date().toISOString();
    
    // Create a real cryptographic hash of the steps to prove non-tampering
    const stepsString = JSON.stringify(plan.steps || []);
    const planHash = crypto.createHash('sha256')
      .update(prompt + stepsString + timestamp)
      .digest('hex');

    // Create a mock Merkle root based on step individual hashes
    const stepHashes = (plan.steps || []).map((step, idx) => 
      crypto.createHash('sha256').update(JSON.stringify(step) + idx).digest('hex')
    );
    
    let merkleRoot = planHash;
    if (stepHashes.length > 0) {
      merkleRoot = crypto.createHash('sha256')
        .update(stepHashes.join(''))
        .digest('hex');
    }

    // Step proof acts as a digital seal for this plan
    const stepProof = crypto.createHash('sha256')
      .update(merkleRoot + this.userEmail + 'armoriq_secure_seal_v1')
      .digest('hex')
      .substring(0, 32);

    return {
      planHash,
      merkleRoot,
      stepProof,
      goal: prompt,
      timestamp
    };
  }

  /**
   * Generates a unique secure cryptographic intent token bound to the sealed plan hash.
   */
  async getIntentToken(captured: CapturedPlan): Promise<string> {
    return `armoriq_intent_token_${crypto.createHash('sha256')
      .update(captured.planHash + this.userEmail + 'armoriq_entropy')
      .digest('hex')
      .substring(0, 16)}`;
  }

  /**
   * Invokes an action, cryptographically verifying its integrity against the sealed intent token and plan.
   */
  async invoke(
    mcp: string, 
    action: string, 
    token: string, 
    params: any, 
    expectedPlanHash: string
  ): Promise<{ status: 'allowed' | 'held' | 'blocked'; reason?: string }> {
    
    // 1. TAMPERING DEMO GUARD: Proving cryptographic verification of the plan hash
    const expectedToken = `armoriq_intent_token_${crypto.createHash('sha256')
      .update(expectedPlanHash + this.userEmail + 'armoriq_entropy')
      .digest('hex')
      .substring(0, 16)}`;

    if (token !== expectedToken) {
      return {
        status: 'blocked',
        reason: `ARMORIQ_TAMPER_DETECTED: Invocation token did not match the sealed plan's cryptographic fingerprint. The intent was modified after plan sealing.`
      };
    }

    // 2. RESOURCE PROTECTION GUARD: Prevent modifications to resources tagged production
    const isProduction = params?.tags?.environment === 'production' || 
                         params?.tags?.env === 'production' ||
                         JSON.stringify(params).toLowerCase().includes('"production"') ||
                         JSON.stringify(params).toLowerCase().includes('"prod"');

    if (isProduction) {
      return {
        status: 'held',
        reason: `ArmorIQ Policy Constraint: Modifying resources in 'production' environments requires explicit supervisor approval.`
      };
    }

    // 3. OUT-OF-SCOPE DESTRUCTIVE ACTION GUARD: High-risk tools
    const highRiskActions = ['rollback_migration', 'delete_volume'];
    if (highRiskActions.includes(action)) {
      return {
        status: 'held',
        reason: `ArmorIQ Policy Constraint: Destructive operation '${action}' detected. Suspended for human verification.`
      };
    }

    // 4. INVALID ACTION EXCEPTION: Any custom malicious action not in the sealed plan
    if (action === 'custom_malicious_action') {
      return {
        status: 'blocked',
        reason: `ARMORIQ_POLICY_VIOLATION: Unsanctioned tool invocation '${action}' is not part of the active, sealed FinOps execution plan.`
      };
    }

    // Default: in-scope actions run automatically
    return {
      status: 'allowed'
    };
  }
}

export class ArmorIQClient {
  private apiKey: string;
  constructor() {
    this.apiKey = process.env.ARMORIQ_API_KEY || 'mock_armoriq_api_key_ghost_cfo';
  }

  forUser(userEmail: string): ArmorIQUserScope {
    return new ArmorIQUserScope(userEmail, this.apiKey);
  }
}
